name: Dependency Review

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  dependency-review:
    name: Dependency Review
    uses: Elavora/.github/.github/workflows/dependency-review.yml@3b7dadedc2f7559cd3ce307904175412b1b2d595
