name: Dependency Review

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  dependency-review:
    name: Dependency Review
    uses: Elavora/.github/.github/workflows/dependency-review.yml@5715f070384cdc70885f1a77670e54fefcfb255d
