name: Release

on:
  pull_request:
    branches: [main]
    types: [closed]

permissions:
  contents: write

jobs:
  release:
    if: github.event.pull_request.merged == true
    uses: Elavora/.github/.github/workflows/release.yml@1e0f42a92a4aafc35522709c30bc4e83acab82f1
    with:
      package_name: elavora/api-storage-s3
      automation_ref: 1e0f42a92a4aafc35522709c30bc4e83acab82f1
    secrets: inherit
