name: Release

on:
  pull_request:
    branches: [main]
    types: [closed]

permissions:
  contents: write

jobs:
  release:
    if: github.event.pull_request.merged == true
    uses: Elavora/.github/.github/workflows/release.yml@3b7dadedc2f7559cd3ce307904175412b1b2d595
    with:
      package_name: elavora/api-storage-s3
      automation_ref: 3b7dadedc2f7559cd3ce307904175412b1b2d595
    secrets: inherit
